name: Build Fork

on:
  push:
    branches:
      - master
      - main
      - develop
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Android APK
        run: |
          # 还原 Keystore 文件
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.keystore
          
          cd android
          ./gradlew assembleExperimentalRelease \
            -PDEFAULT_SERVER_URL="${{ env.DEFAULT_SERVER_URL }}" \
            -PKEYSTORE=my-release-key.keystore \
            -PKEYSTORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}" \
            -PKEY_ALIAS="${{ secrets.KEY_ALIAS }}" \
            -PKEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"
        env:
          VERSIONCODE: 1
          APPLICATION_ID: chat.rocket.reactnative
          DEFAULT_SERVER_URL: ${{ vars.DEFAULT_SERVER_URL || 'https://open.rocket.chat' }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-experimental-release
          path: android/app/build/outputs/apk/experimental/release/*.apk
